// Code generated by sdkcodegen; DO NOT EDIT.

package workwx

// reqCreateDoc 新建文档请求
type reqCreateDoc struct {
	// SpaceID 空间spaceid。若指定spaceid，则fatherid也要同时指定
	SpaceID string `json:"spaceid,omitempty"`
	// FatherID 	父目录fileid, 在根目录时为空间spaceid
	FatherID string `json:"fatherid"`
	// DocType 文档类型, 3:文档 4:表格 10:智能表格
	DocType DocType `json:"doc_type"`
	// DocName 文档名字（注意：文件名最多填255个字符, 超过255个字符会被截断）
	DocName string `json:"doc_name"`
	// AdminUsers 文档管理员userid
	AdminUsers []string `json:"admin_users"`
}

// DocType 文档类型
type DocType uint32

const (
	DocTypeDoc        DocType = 3  // 文档
	DocTypeSheet      DocType = 4  // 表格
	DocTypeSmartSheet DocType = 10 // 智能表格
)

// respCreateDoc 新建文档返回
type respCreateDoc struct {
	// respCommon 通用响应
	respCommon
	// URL 新建文档的访问链接
	URL string `json:"url"`
	// DocID 新建文档的docid
	DocID string `json:"docid"`
}

// reqRenameDoc 重命名文档请求
type reqRenameDoc struct {
	// DocID 文档docid（docid、formid只能填其中一个），仅可修改应用自己创建的文档
	DocID string `json:"docid"`
	// FormID 收集表id（docid、formid只能填其中一个），仅可修改应用自己创建的收集表
	FormID string `json:"formid"`
	// NewName 重命名后的文档名（注意：文档名最多填255个字符，英文算1个，汉字算2个，超过255个字符会被截断）
	NewName string `json:"new_name"`
}

// reqDelDoc 删除文档请求
type reqDelDoc struct {
	// DocID 文档docid（docid、formid只能填其中一个），仅可删除应用自己创建的文档
	DocID string `json:"docid,omitempty"`
	// FormID 收集表id（docid、formid只能填其中一个），仅可删除应用自己创建的收集表
	FormID string `json:"formid,omitempty"`
}

// reqGetDocBaseInfo 获取文档基础信息请求
type reqGetDocBaseInfo struct {
	// DocID 文档docid
	DocID string `json:"docid"`
}

// respGetDocBaseInfo 获取文档基础信息返回
type respGetDocBaseInfo struct {
	// respCommon 通用响应
	respCommon
	// DocBaseInfo 文档基础信息
	DocBaseInfo DocBaseInfo `json:"doc_base_info"`
}

// DocBaseInfo 文档基础信息
type DocBaseInfo struct {
	// DocID 文档docid
	DocID string `json:"docid"`
	// DocName 文档名字
	DocName string `json:"doc_name"`
	// CreateTime 文档创建时间
	CreateTime uint64 `json:"create_time"`
	// ModifyTime 文档最后修改时间
	ModifyTime uint64 `json:"modify_time"`
	// DocType 文档类型
	DocType DocType `json:"doc_type"`
}

// reqDocShare 分享文档请求
type reqDocShare struct {
	// DocID 文档id（docid、formid只能填其中一个）
	DocID string `json:"docid,omitempty"`
	// FormID 收集表id（docid、formid只能填其中一个）
	FormID string `json:"formid,omitempty"`
}

// respDocShare 分享文档返回
type respDocShare struct {
	// respCommon 通用响应
	respCommon
	// ShareURL 文档分享链接
	ShareURL string `json:"share_url"`
}

// reqGetSmartsheet 查询子表请求
type reqGetSmartsheet struct {
	// DocID 文档的docid
	DocID string `json:"docid"`
	// SheetID 指定子表ID查询
	SheetID string `json:"sheet_id"`
	// NeedAllTypeSheet 获取所有类型子表
	NeedAllTypeSheet bool `json:"need_all_type_sheet"`
}

// respGetSmartsheet 查询子表返回
type respGetSmartsheet struct {
	// respCommon 通用响应
	respCommon
	// SheetList 智能表信息列表
	SheetList []SheetInfo `json:"sheet_list"`
}

// SheetInfo 子表信息
type SheetInfo struct {
	// SheetID 子表id
	SheetID string `json:"sheet_id"`
	// Title 子表名称
	Title string `json:"title"`
	// IsVisible 子表是否可见
	IsVisible bool `json:"is_visible"`
	// SheetType 子表类型。"dashboard" 仪表盘。"external" 说明页，"smartsheet" 智能表
	SheetType string `json:"type"`
}

// reqListSmartsheetViews 获取智能表格视图列表请求
type reqListSmartsheetViews struct {
	// DocID 文档的docid
	DocID string `json:"docid"`
	// SheetID Smartsheet子表ID
	SheetID string `json:"sheet_id"`
	// ViewIDs 需要查询的视图ID数组
	ViewIDs []string `json:"view_ids"`
	// Offset 偏移量，初始值为0
	Offset uint32 `json:"offset"`
	// Limit 分页大小，不填或0时，如果总数大于1000，一次性返回1000个视图，否则返回全部视图；最大值为1000
	Limit uint32 `json:"limit"`
}

// respListSmartsheetViews 获取智能表格视图列表响应
type respListSmartsheetViews struct {
	// respCommon 通用响应
	respCommon
	// Total 符合筛选条件的视图总数
	Total uint32 `json:"total"`
	// HasMore 是否还有更多项
	HasMore bool `json:"has_more"`
	// Next 下次下一个搜索结果的偏移量
	Next uint32 `json:"next"`
	// Views 视图数据
	Views []View `json:"views"`
}

// View 视图信息
type View struct {
	// ViewID 视图ID
	ViewID string `json:"view_id"`
	// ViewTitle 视图标题
	ViewTitle string `json:"view_title"`
	// ViewType 视图类型
	ViewType ViewType `json:"view_type"`
	// Property 视图属性
	Property *ViewProperty `json:"property"`
}

// ViewType 视图类型
type ViewType string

const (
	ViewTypeUnknown ViewType = "VEW_UNKNOWN"       // 未知类型视图
	ViewTypeGrid    ViewType = "VIEW_TYPE_GRID"    // 网格视图
	ViewTypeKanban  ViewType = "VIEW_TYPE_KANBAN"  // 看板视图
	ViewTypeGallery ViewType = "VIEW_TYPE_GALLERY" // 画册视图
	ViewTypeGantt   ViewType = "VIEW_TYPE_GANTT"   // 甘特视图
)

// ViewProperty 视图属性
type ViewProperty struct {
	// AutoSort 记录变更后自动重新排序
	AutoSort bool `json:"auto_sort"`
	// SortSpec 排序设置
	SortSpec *SortSpec `json:"sort_spec"`
	// GroupSpec 分组设置
	GroupSpec *GroupSpec `json:"group_spec"`
	// FilterSpec 过滤设置
	FilterSpec *FilterSpec `json:"filter_spec"`
	// IsFieldStatEnabled 是否使用数据统计
	IsFieldStatEnabled bool `json:"is_field_stat_enabled"`
	// FieldVisibility 字段可见性
	FieldVisibility map[string]bool `json:"field_visibility"`
	// FrozenFieldCount 冻结列数量，从首列开始
	FrozenFieldCount int32 `json:"frozen_field_count"`
}

// SortSpec 排序设置
type SortSpec struct {
	// SortInfos 参与排序的字段列表
	SortInfos []SortInfo `json:"sort_infos"`
}

// SortInfo 排序信息
type SortInfo struct {
	// FieldID 字段id
	FieldID string `json:"field_id"`
	// Desc 是否降序
	Desc bool `json:"desc"`
}

// GroupSpec 分组设置
type GroupSpec struct {
	// Groups 参与分组的字段列表
	Groups []GroupInfo `json:"groups"`
}

// GroupInfo 分组信息
type GroupInfo struct {
	// FieldID 字段id
	FieldID string `json:"field_id"`
	// Desc 是否降序
	Desc bool `json:"desc"`
}

// FilterSpec 过滤设置
type FilterSpec struct {
	// Conjunction 多个conditions之间是以and("CONJUNCTION_AND")还是or("CONJUNCTION_OR")进行组合
	Conjunction string `json:"conjunction"`
	// Conditions 判断条件
	Conditions []Condition `json:"conditions"`
}

// Condition 过滤条件
type Condition struct {
	// FieldID 字段ID
	FieldID string `json:"field_id"`
	// FieldType 字段类型
	FieldType string `json:"field_type"`
	// Operator 判断类型
	Operator string `json:"operator"`
	// StringValue 文本值
	StringValue *StringValue `json:"string_value"`
	// NumberValue 数字值
	NumberValue *NumberValue `json:"number_value"`
	// BoolValue 布尔值
	BoolValue *BoolValue `json:"bool_value"`
	// UserValue 用户值
	UserValue *UserValue `json:"user_value"`
	// DateTimeValue 日期时间值
	DateTimeValue *FilterDataTimeValue `json:"date_time_value"`
}

// StringValue 字符串值
type StringValue struct {
	// Value 字符串值数组
	Value []string `json:"value"`
}

// NumberValue 数字值
type NumberValue struct {
	// Value 数字值
	Value float64 `json:"value"`
}

// BoolValue 布尔值
type BoolValue struct {
	// Value 布尔值
	Value bool `json:"value"`
}

// UserValue 用户值
type UserValue struct {
	// Value 用户ID数组
	Value []string `json:"value"`
}

// FilterDataTimeValue 日期时间值
type FilterDataTimeValue struct {
	// Type 日期类型
	Type string `json:"type"`
	// Value 具体日期值，type为具体日期或具体日期范围时必填
	Value []string `json:"value"`
}

// execWedocCreatDoc 新建文档
func (c *WorkwxApp) execWedocCreatDoc(req reqCreateDoc) (respCreateDoc, error) {
	var resp respCreateDoc
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/create_doc", req, &resp, true)
	if err != nil {
		return respCreateDoc{}, err
	}

	return resp, nil
}

// execWedocRenameDoc 重命名文档
func (c *WorkwxApp) execWedocRenameDoc(req reqRenameDoc) (respCommon, error) {
	var resp respCommon
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/rename_doc", req, &resp, true)
	if err != nil {
		return respCommon{}, err
	}

	return resp, nil
}

// execWedocDelDoc 删除文档
func (c *WorkwxApp) execWedocDelDoc(req reqDelDoc) (respCommon, error) {
	var resp respCommon
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/del_doc", req, &resp, true)
	if err != nil {
		return respCommon{}, err
	}

	return resp, nil
}

// execWedocGetDocBaseInfo 获取文档基础信息
func (c *WorkwxApp) execWedocGetDocBaseInfo(req reqGetDocBaseInfo) (respGetDocBaseInfo, error) {
	var resp respGetDocBaseInfo
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/get_doc_base_info", req, &resp, true)
	if err != nil {
		return respGetDocBaseInfo{}, err
	}

	return resp, nil
}

// execWedocDocShare 分享文档
func (c *WorkwxApp) execWedocDocShare(req reqDocShare) (respDocShare, error) {
	var resp respDocShare
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/doc_share", req, &resp, true)
	if err != nil {
		return respDocShare{}, err
	}

	return resp, nil
}

// execWedocSmartsheetGetSheet 查询子表
func (c *WorkwxApp) execWedocSmartsheetGetSheet(req reqGetSmartsheet) (respGetSmartsheet, error) {
	var resp respGetSmartsheet
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/smartsheet/get_sheet", req, &resp, true)
	if err != nil {
		return respGetSmartsheet{}, err
	}

	return resp, nil
}

// execWedocSmartsheetGetViews 查询视图
func (c *WorkwxApp) execWedocSmartsheetGetViews(req reqListSmartsheetViews) (respListSmartsheetViews, error) {
	var resp respListSmartsheetViews
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/smartsheet/get_views", req, &resp, true)
	if err != nil {
		return respListSmartsheetViews{}, err
	}

	return resp, nil
}
