// Code generated by sdkcodegen; DO NOT EDIT.

package workwx

// reqCreateDoc 新建文档请求
type reqCreateDoc struct {
	// SpaceID 空间spaceid。若指定spaceid，则fatherid也要同时指定
	SpaceID string `json:"spaceid,omitempty"`
	// FatherID 	父目录fileid, 在根目录时为空间spaceid
	FatherID string `json:"fatherid"`
	// DocType 文档类型, 3:文档 4:表格 10:智能表格
	DocType DocType `json:"doc_type"`
	// DocName 文档名字（注意：文件名最多填255个字符, 超过255个字符会被截断）
	DocName string `json:"doc_name"`
	// AdminUsers 文档管理员userid
	AdminUsers []string `json:"admin_users"`
}

// DocType 文档类型
type DocType uint32

const (
	DocTypeDoc        DocType = 3  // 文档
	DocTypeSheet      DocType = 4  // 表格
	DocTypeSmartSheet DocType = 10 // 智能表格
)

// respCreateDoc 新建文档返回
type respCreateDoc struct {
	// respCommon 通用响应
	respCommon
	// URL 新建文档的访问链接
	URL string `json:"url"`
	// DocID 新建文档的docid
	DocID string `json:"docid"`
}

// reqRenameDoc 重命名文档请求
type reqRenameDoc struct {
	// DocID 文档docid（docid、formid只能填其中一个），仅可修改应用自己创建的文档
	DocID string `json:"docid"`
	// FormID 收集表id（docid、formid只能填其中一个），仅可修改应用自己创建的收集表
	FormID string `json:"formid"`
	// NewName 重命名后的文档名（注意：文档名最多填255个字符，英文算1个，汉字算2个，超过255个字符会被截断）
	NewName string `json:"new_name"`
}

// reqDelDoc 删除文档请求
type reqDelDoc struct {
	// DocID 文档docid（docid、formid只能填其中一个），仅可删除应用自己创建的文档
	DocID string `json:"docid,omitempty"`
	// FormID 收集表id（docid、formid只能填其中一个），仅可删除应用自己创建的收集表
	FormID string `json:"formid,omitempty"`
}

// reqGetDocBaseInfo 获取文档基础信息请求
type reqGetDocBaseInfo struct {
	// DocID 文档docid
	DocID string `json:"docid"`
}

// respGetDocBaseInfo 获取文档基础信息返回
type respGetDocBaseInfo struct {
	// respCommon 通用响应
	respCommon
	// DocBaseInfo 文档基础信息
	DocBaseInfo DocBaseInfo `json:"doc_base_info"`
}

// DocBaseInfo 文档基础信息
type DocBaseInfo struct {
	// DocID 文档docid
	DocID string `json:"docid"`
	// DocName 文档名字
	DocName string `json:"doc_name"`
	// CreateTime 文档创建时间
	CreateTime uint64 `json:"create_time"`
	// ModifyTime 文档最后修改时间
	ModifyTime uint64 `json:"modify_time"`
	// DocType 文档类型
	DocType DocType `json:"doc_type"`
}

// reqDocShare 分享文档请求
type reqDocShare struct {
	// DocID 文档id（docid、formid只能填其中一个）
	DocID string `json:"docid,omitempty"`
	// FormID 收集表id（docid、formid只能填其中一个）
	FormID string `json:"formid,omitempty"`
}

// respDocShare 分享文档返回
type respDocShare struct {
	// respCommon 通用响应
	respCommon
	// ShareURL 文档分享链接
	ShareURL string `json:"share_url"`
}

// reqGetSmartsheet 查询子表请求
type reqGetSmartsheet struct {
	// DocID 文档的docid
	DocID string `json:"docid"`
	// SheetID 指定子表ID查询
	SheetID string `json:"sheet_id"`
	// NeedAllTypeSheet 获取所有类型子表
	NeedAllTypeSheet bool `json:"need_all_type_sheet"`
}

// respGetSmartsheet 查询子表返回
type respGetSmartsheet struct {
	// respCommon 通用响应
	respCommon
	// SheetList 智能表信息列表
	SheetList []SheetInfo `json:"sheet_list"`
}

// SheetInfo 子表信息
type SheetInfo struct {
	// SheetID 子表id
	SheetID string `json:"sheet_id"`
	// Title 子表名称
	Title string `json:"title"`
	// IsVisible 子表是否可见
	IsVisible bool `json:"is_visible"`
	// SheetType 子表类型。"dashboard" 仪表盘。"external" 说明页，"smartsheet" 智能表
	SheetType string `json:"type"`
}

// reqListSmartsheetViews 获取智能表格视图列表请求
type reqListSmartsheetViews struct {
	// DocID 文档的docid
	DocID string `json:"docid"`
	// SheetID Smartsheet子表ID
	SheetID string `json:"sheet_id"`
	// ViewIDs 需要查询的视图ID数组
	ViewIDs []string `json:"view_ids"`
	// Offset 偏移量，初始值为0
	Offset uint32 `json:"offset"`
	// Limit 分页大小，不填或0时，如果总数大于1000，一次性返回1000个视图，否则返回全部视图；最大值为1000
	Limit uint32 `json:"limit"`
}

// respListSmartsheetViews 获取智能表格视图列表响应
type respListSmartsheetViews struct {
	// respCommon 通用响应
	respCommon
	// Total 符合筛选条件的视图总数
	Total uint32 `json:"total"`
	// HasMore 是否还有更多项
	HasMore bool `json:"has_more"`
	// Next 下次下一个搜索结果的偏移量
	Next uint32 `json:"next"`
	// Views 视图数据
	Views []View `json:"views"`
}

// View 视图信息
type View struct {
	// ViewID 视图ID
	ViewID string `json:"view_id"`
	// ViewTitle 视图标题
	ViewTitle string `json:"view_title"`
	// ViewType 视图类型
	ViewType ViewType `json:"view_type"`
	// Property 视图属性
	Property *ViewProperty `json:"property"`
}

// ViewType 视图类型
type ViewType string

const (
	ViewTypeUnknown ViewType = "VEW_UNKNOWN"       // 未知类型视图
	ViewTypeGrid    ViewType = "VIEW_TYPE_GRID"    // 网格视图
	ViewTypeKanban  ViewType = "VIEW_TYPE_KANBAN"  // 看板视图
	ViewTypeGallery ViewType = "VIEW_TYPE_GALLERY" // 画册视图
	ViewTypeGantt   ViewType = "VIEW_TYPE_GANTT"   // 甘特视图
)

// ViewProperty 视图属性
type ViewProperty struct {
	// AutoSort 记录变更后自动重新排序
	AutoSort bool `json:"auto_sort"`
	// SortSpec 排序设置
	SortSpec *SortSpec `json:"sort_spec"`
	// GroupSpec 分组设置
	GroupSpec *GroupSpec `json:"group_spec"`
	// FilterSpec 过滤设置
	FilterSpec *FilterSpec `json:"filter_spec"`
	// IsFieldStatEnabled 是否使用数据统计
	IsFieldStatEnabled bool `json:"is_field_stat_enabled"`
	// FieldVisibility 字段可见性
	FieldVisibility map[string]bool `json:"field_visibility"`
	// FrozenFieldCount 冻结列数量，从首列开始
	FrozenFieldCount int32 `json:"frozen_field_count"`
}

// SortSpec 排序设置
type SortSpec struct {
	// SortInfos 参与排序的字段列表
	SortInfos []SortInfo `json:"sort_infos"`
}

// SortInfo 排序信息
type SortInfo struct {
	// FieldID 字段id
	FieldID string `json:"field_id"`
	// Desc 是否降序
	Desc bool `json:"desc"`
}

// GroupSpec 分组设置
type GroupSpec struct {
	// Groups 参与分组的字段列表
	Groups []GroupInfo `json:"groups"`
}

// GroupInfo 分组信息
type GroupInfo struct {
	// FieldID 字段id
	FieldID string `json:"field_id"`
	// Desc 是否降序
	Desc bool `json:"desc"`
}

// FilterSpec 过滤设置
type FilterSpec struct {
	// Conjunction 多个conditions之间是以and("CONJUNCTION_AND")还是or("CONJUNCTION_OR")进行组合
	Conjunction string `json:"conjunction"`
	// Conditions 判断条件
	Conditions []Condition `json:"conditions"`
}

// Condition 过滤条件
type Condition struct {
	// FieldID 字段ID
	FieldID string `json:"field_id"`
	// FieldType 字段类型
	FieldType string `json:"field_type"`
	// Operator 判断类型
	Operator string `json:"operator"`
	// StringValue 文本值
	StringValue *StringValue `json:"string_value"`
	// NumberValue 数字值
	NumberValue *NumberValue `json:"number_value"`
	// BoolValue 布尔值
	BoolValue *BoolValue `json:"bool_value"`
	// UserValue 用户值
	UserValue *UserValue `json:"user_value"`
	// DateTimeValue 日期时间值
	DateTimeValue *FilterDataTimeValue `json:"date_time_value"`
}

// StringValue 字符串值
type StringValue struct {
	// Value 字符串值数组
	Value []string `json:"value"`
}

// NumberValue 数字值
type NumberValue struct {
	// Value 数字值
	Value float64 `json:"value"`
}

// BoolValue 布尔值
type BoolValue struct {
	// Value 布尔值
	Value bool `json:"value"`
}

// UserValue 用户值
type UserValue struct {
	// Value 用户ID数组
	Value []string `json:"value"`
}

// FilterDataTimeValue 日期时间值
type FilterDataTimeValue struct {
	// Type 日期类型
	Type string `json:"type"`
	// Value 具体日期值，type为具体日期或具体日期范围时必填
	Value []string `json:"value"`
}

// reqListSmartsheetFields 获取智能表格字段请求
type reqListSmartsheetFields struct {
	// DocID 文档的docid
	DocID string `json:"docid"`
	// SheetID 表格ID
	SheetID string `json:"sheet_id"`
	// ViewID 视图ID
	ViewID string `json:"view_id,omitempty"`
	// FieldIDs 由字段ID组成的数组
	FieldIDs []string `json:"field_ids,omitempty"`
	// FieldTitles 由字段标题组成的数组
	FieldTitles []string `json:"field_titles,omitempty"`
	// Offset 偏移量，初始值为0
	Offset int `json:"offset,omitempty"`
	// Limit 分页大小，不填或0时，如果总数大于1000，一次性返回1000个字段，当总数小于1000时，返回全部字段；最大值为1000
	Limit int `json:"limit,omitempty"`
}

// respListSmartsheetFields 获取智能表格字段响应
type respListSmartsheetFields struct {
	// respCommon 通用响应
	respCommon
	// Total 字段总数
	Total int `json:"total"`
	// Fields 字段详情
	Fields []Field `json:"fields"`
}

// Field 字段信息
type Field struct {
	// FieldID 字段ID
	FieldID string `json:"field_id"`
	// FieldTitle 字段标题
	FieldTitle string `json:"field_title"`
	// FieldType 字段类型
	FieldType FieldType `json:"field_type"`
	// PropertyNumber 数字类型的字段属性
	PropertyNumber *NumberFieldProperty `json:"property_number,omitempty"`
	// PropertyCheckbox 复选框类型的字段属性
	PropertyCheckbox *CheckboxFieldProperty `json:"property_checkbox,omitempty"`
	// PropertyDateTime 日期类型的字段属性
	PropertyDateTime *DateTimeFieldProperty `json:"property_date_time,omitempty"`
	// PropertyAttachment 文件类型的字段属性
	PropertyAttachment *AttachmentFieldProperty `json:"property_attachment,omitempty"`
	// PropertyUser 人员类型的字段属性
	PropertyUser *UserFieldProperty `json:"property_user,omitempty"`
	// PropertyURL 超链接类型的字段属性
	PropertyURL *UrlFieldProperty `json:"property_url,omitempty"`
	// PropertySelect 多选类型的字段属性
	PropertySelect *SelectFieldProperty `json:"property_select,omitempty"`
	// PropertyCreatedTime 创建时间类型的字段属性
	PropertyCreatedTime *CreatedTimeFieldProperty `json:"property_created_time,omitempty"`
	// PropertyModifiedTime 最后编辑时间类型的字段属性
	PropertyModifiedTime *ModifiedTimeFieldProperty `json:"property_modified_time,omitempty"`
	// PropertyProgress 进度类型的字段属性
	PropertyProgress *ProgressFieldProperty `json:"property_progress,omitempty"`
	// PropertySingleSelect 单选类型的字段属性
	PropertySingleSelect *SingleSelectFieldProperty `json:"property_single_select,omitempty"`
	// PropertyReference 引用类型的字段属性
	PropertyReference *ReferenceFieldProperty `json:"property_reference,omitempty"`
	// PropertyLocation 地理位置类型的字段属性
	PropertyLocation *LocationFieldProperty `json:"property_location,omitempty"`
	// PropertyAutoNumber 自动编号类型的字段属性
	PropertyAutoNumber *AutoNumberFieldProperty `json:"property_auto_number,omitempty"`
	// PropertyCurrency 货币类型的字段属性
	PropertyCurrency *CurrencyFieldProperty `json:"property_currency,omitempty"`
	// PropertyWwGroup 群类型的字段属性
	PropertyWwGroup *WwGroupFieldProperty `json:"property_ww_group,omitempty"`
	// PropertyPercentage 百分数类型的字段属性
	PropertyPercentage *PercentageFieldProperty `json:"property_percentage,omitempty"`
}

// FieldType 字段类型
type FieldType string

const (
	FieldTypeText         FieldType = "FIELD_TYPE_TEXT"          // 文本
	FieldTypeNumber       FieldType = "FIELD_TYPE_NUMBER"        // 数字
	FieldTypeCheckbox     FieldType = "FIELD_TYPE_CHECKBOX"      // 复选框
	FieldTypeDateTime     FieldType = "FIELD_TYPE_DATE_TIME"     // 日期
	FieldTypeImage        FieldType = "FIELD_TYPE_IMAGE"         // 图片
	FieldTypeAttachment   FieldType = "FIELD_TYPE_ATTACHMENT"    // 文件
	FieldTypeUser         FieldType = "FIELD_TYPE_USER"          // 成员
	FieldTypeURL          FieldType = "FIELD_TYPE_URL"           // 超链接
	FieldTypeSelect       FieldType = "FIELD_TYPE_SELECT"        // 多选
	FieldTypeCreatedUser  FieldType = "FIELD_TYPE_CREATED_USER"  // 创建人
	FieldTypeModifiedUser FieldType = "FIELD_TYPE_MODIFIED_USER" // 最后编辑人
	FieldTypeCreatedTime  FieldType = "FIELD_TYPE_CREATED_TIME"  // 创建时间
	FieldTypeModifiedTime FieldType = "FIELD_TYPE_MODIFIED_TIME" // 最后编辑时间
	FieldTypeProgress     FieldType = "FIELD_TYPE_PROGRESS"      // 进度
	FieldTypePhoneNumber  FieldType = "FIELD_TYPE_PHONE_NUMBER"  // 电话
	FieldTypeEmail        FieldType = "FIELD_TYPE_EMAIL"         // 邮件
	FieldTypeSingleSelect FieldType = "FIELD_TYPE_SINGLE_SELECT" // 单选
	FieldTypeReference    FieldType = "FIELD_TYPE_REFERENCE"     // 关联
	FieldTypeLocation     FieldType = "FIELD_TYPE_LOCATION"      // 地理位置
	FieldTypeFormula      FieldType = "FIELD_TYPE_FORMULA"       // 公式
	FieldTypeCurrency     FieldType = "FIELD_TYPE_CURRENCY"      // 货币
	FieldTypeWwGroup      FieldType = "FIELD_TYPE_WWGROUP"       // 群
	FieldTypeAutoNumber   FieldType = "FIELD_TYPE_AUTONUMBER"    // 自动编号
	FieldTypePercentage   FieldType = "FIELD_TYPE_PERCENTAGE"    // 百分数
)

// NumberFieldProperty 数字类型字段属性
type NumberFieldProperty struct {
	// DecimalPlaces 表示小数点的位数，即数字精度
	DecimalPlaces int `json:"decimal_places"`
	// UseSeparate 是否使用千位符，设置此属性后数字字段将以英文逗号分隔千分位，如1,000
	UseSeparate bool `json:"use_separate"`
}

// CheckboxFieldProperty 复选框类型字段属性
type CheckboxFieldProperty struct {
	// Checked 新增时是否默认勾选
	Checked bool `json:"checked"`
}

// DateTimeFieldProperty 日期类型字段属性
type DateTimeFieldProperty struct {
	// Format 设置日期格式
	Format string `json:"format"`
	// AutoFill 新建记录时，是否自动填充时间
	AutoFill bool `json:"auto_fill"`
}

// AttachmentFieldProperty 文件类型字段属性
type AttachmentFieldProperty struct {
	// DisplayMode 展示样式
	DisplayMode string `json:"display_mode"`
}

// UserFieldProperty 成员类型字段属性
type UserFieldProperty struct {
	// IsMultiple 允许添加多个人员
	IsMultiple bool `json:"is_multiple"`
	// IsNotified 添加人员时通知用户，关闭后不通知
	IsNotified bool `json:"is_notified"`
}

// UrlFieldProperty 超链接类型字段属性
type UrlFieldProperty struct {
	// Type 超链接展示样式
	Type string `json:"type"`
}

// SelectFieldProperty 多选类型字段属性
type SelectFieldProperty struct {
	// IsQuickAdd 是否允许填写时新增选项
	IsQuickAdd bool `json:"is_quick_add"`
	// Options 多选选项的格式设置
	Options []Option `json:"options"`
}

// CreatedTimeFieldProperty 创建时间类型字段属性
type CreatedTimeFieldProperty struct {
	// Format 设置日期格式
	Format string `json:"format"`
}

// ModifiedTimeFieldProperty 最后编辑时间类型字段属性
type ModifiedTimeFieldProperty struct {
	// Format 设置日期格式
	Format string `json:"format"`
}

// ProgressFieldProperty 进度类型字段属性
type ProgressFieldProperty struct {
	// DecimalPlaces 小数位数
	DecimalPlaces int `json:"decimal_places"`
}

// SingleSelectFieldProperty 单选类型字段属性
type SingleSelectFieldProperty struct {
	// IsQuickAdd 是否允许填写时新增选项
	IsQuickAdd bool `json:"is_quick_add"`
	// Options 单选选项的格式设置
	Options []Option `json:"options"`
}

// ReferenceFieldProperty 关联字段属性
type ReferenceFieldProperty struct {
	// SubID 关联的子表id，为空时，表示关联本子表
	SubID string `json:"sub_id"`
	// FiledID 关联的字段id
	FiledID string `json:"filed_id"`
	// IsMultiple 是否允许多选
	IsMultiple bool `json:"is_multiple"`
	// ViewID 视图id
	ViewID string `json:"view_id"`
}

// LocationFieldProperty 地理位置字段属性
type LocationFieldProperty struct {
	// InputType 输入类型
	InputType string `json:"input_type"`
}

// AutoNumberFieldProperty 自动编号字段属性
type AutoNumberFieldProperty struct {
	// Type 输入类型
	Type string `json:"type"`
	// Rules 自定义规则
	Rules []NumberRule `json:"rules"`
	// ReformatExistingRecord 是否应用于已有编号
	ReformatExistingRecord bool `json:"reformat_existing_record"`
}

// CurrencyFieldProperty 货币类型字段属性
type CurrencyFieldProperty struct {
	// CurrencyType 输入类型
	CurrencyType string `json:"currency_type"`
	// DecimalPlaces 表示小数点的位数，即数字精度
	DecimalPlaces int `json:"decimal_places"`
	// UseSeparate 是否使用千位符
	UseSeparate bool `json:"use_separate"`
}

// WwGroupFieldProperty 群类型的字段属性
type WwGroupFieldProperty struct {
	// AllowMultiple 是否允许多个群聊
	AllowMultiple bool `json:"allow_multiple"`
}

// PercentageFieldProperty 百分数类型的字段属性
type PercentageFieldProperty struct {
	// DecimalPlaces 表示小数点的位数，即数字精度
	DecimalPlaces int `json:"decimal_places"`
	// UseSeparate 是否使用千位符
	UseSeparate bool `json:"use_separate"`
}

// Option 选项参数
type Option struct {
	// ID 选项ID
	ID string `json:"id"`
	// Text 要填写的选项内容
	Text string `json:"text"`
	// Style 选项颜色
	Style int `json:"style"`
}

// NumberRule 自动编号规则
type NumberRule struct {
	// Type 规则类型
	Type string `json:"type"`
	// Value 存放创建时间格式或固定字符，自增数字位数
	Value string `json:"value"`
}

// reqSmartsheetGetRecords 查询记录请求
type reqSmartsheetGetRecords struct {
	// DocID 文档的docid
	DocID string `json:"docid"`
	// SheetID Smartsheet 子表ID
	SheetID string `json:"sheet_id"`
	// ViewID 视图 ID
	ViewID string `json:"view_id,omitempty"`
	// RecordIDs 由记录 ID 组成的 JSON 数组
	RecordIDs []string `json:"record_ids,omitempty"`
	// KeyType 返回记录中单元格的key类型
	KeyType CellValueKeyType `json:"key_type,omitempty"`
	// FieldTitles 返回指定列，由字段标题组成的 JSON 数组 ，key_type 为 CELL_VALUE_KEY_TYPE_FIELD_TITLE 时有效
	FieldTitles []string `json:"field_titles,omitempty"`
	// FieldIDs 返回指定列，由字段 ID 组成的 JSON 数组 ，key_type 为 CELL_VALUE_KEY_TYPE_FIELD_ID 时有效
	FieldIDs []string `json:"field_ids,omitempty"`
	// Sort 对返回记录进行排序
	Sort []Sort `json:"sort,omitempty"`
	// Offset 偏移量，初始值为 0
	Offset uint32 `json:"offset,omitempty"`
	// Limit 分页大小，当不填写该参数或将该参数设置为 0 时，如果总数大于 1000，一次性返回 1000 行记录，当总数小于 1000 时，返回全部记录；limit 最大值为 1000
	Limit uint32 `json:"limit,omitempty"`
}

// CellValueKeyType 记录中key的类型
type CellValueKeyType string

const (
	CellValueKeyTypeFieldTitle CellValueKeyType = "CELL_VALUE_KEY_TYPE_FIELD_TITLE" // key用字段标题表示
	CellValueKeyTypeFieldID    CellValueKeyType = "CELL_VALUE_KEY_TYPE_FIELD_ID"    // key用字段 ID 表示
)

// Sort 排序参数
type Sort struct {
	// FieldTitle 需要排序的字段标题
	FieldTitle string `json:"field_title"`
	// Desc 是否进行降序排序，默认值为 false
	Desc bool `json:"desc,omitempty"`
}

// respSmartsheetGetRecords 查询记录响应
type respSmartsheetGetRecords struct {
	// respCommon 通用响应
	respCommon
	// Total 符合筛选条件的视图总数
	Total uint32 `json:"total"`
	// HasMore 是否还有更多项
	HasMore bool `json:"has_more"`
	// Next 下次下一个搜索结果的偏移量
	Next uint32 `json:"next"`
	// Records 由查询记录的具体内容组成的 JSON 数组
	Records []Record `json:"records"`
}

// Record 记录信息
type Record struct {
	// RecordID 记录 ID
	RecordID string `json:"record_id"`
	// CreateTime 记录的创建时间
	CreateTime string `json:"create_time"`
	// UpdateTime 记录的更新时间
	UpdateTime string `json:"update_time"`
	// Values 记录的具体内容，key为字段标题或字段ID，value类型根据字段类型不同而异
	Values map[string]interface{} `json:"values"`
	// CreatorName 创建者名字
	CreatorName string `json:"creator_name"`
	// UpdaterName 最后编辑者名字
	UpdaterName string `json:"updater_name"`
}

// execWedocCreatDoc 新建文档
func (c *WorkwxApp) execWedocCreatDoc(req reqCreateDoc) (respCreateDoc, error) {
	var resp respCreateDoc
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/create_doc", req, &resp, true)
	if err != nil {
		return respCreateDoc{}, err
	}

	return resp, nil
}

// execWedocRenameDoc 重命名文档
func (c *WorkwxApp) execWedocRenameDoc(req reqRenameDoc) (respCommon, error) {
	var resp respCommon
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/rename_doc", req, &resp, true)
	if err != nil {
		return respCommon{}, err
	}

	return resp, nil
}

// execWedocDelDoc 删除文档
func (c *WorkwxApp) execWedocDelDoc(req reqDelDoc) (respCommon, error) {
	var resp respCommon
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/del_doc", req, &resp, true)
	if err != nil {
		return respCommon{}, err
	}

	return resp, nil
}

// execWedocGetDocBaseInfo 获取文档基础信息
func (c *WorkwxApp) execWedocGetDocBaseInfo(req reqGetDocBaseInfo) (respGetDocBaseInfo, error) {
	var resp respGetDocBaseInfo
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/get_doc_base_info", req, &resp, true)
	if err != nil {
		return respGetDocBaseInfo{}, err
	}

	return resp, nil
}

// execWedocDocShare 分享文档
func (c *WorkwxApp) execWedocDocShare(req reqDocShare) (respDocShare, error) {
	var resp respDocShare
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/doc_share", req, &resp, true)
	if err != nil {
		return respDocShare{}, err
	}

	return resp, nil
}

// execWedocSmartsheetGetSheet 查询子表
func (c *WorkwxApp) execWedocSmartsheetGetSheet(req reqGetSmartsheet) (respGetSmartsheet, error) {
	var resp respGetSmartsheet
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/smartsheet/get_sheet", req, &resp, true)
	if err != nil {
		return respGetSmartsheet{}, err
	}

	return resp, nil
}

// execWedocSmartsheetGetViews 查询视图
func (c *WorkwxApp) execWedocSmartsheetGetViews(req reqListSmartsheetViews) (respListSmartsheetViews, error) {
	var resp respListSmartsheetViews
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/smartsheet/get_views", req, &resp, true)
	if err != nil {
		return respListSmartsheetViews{}, err
	}

	return resp, nil
}

// execWedocSmartsheetGetFields 查询字段
func (c *WorkwxApp) execWedocSmartsheetGetFields(req reqListSmartsheetFields) (respListSmartsheetFields, error) {
	var resp respListSmartsheetFields
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/smartsheet/get_fields", req, &resp, true)
	if err != nil {
		return respListSmartsheetFields{}, err
	}

	return resp, nil
}

// execWedocSmartsheetGetRecords 查询记录
func (c *WorkwxApp) execWedocSmartsheetGetRecords(req reqSmartsheetGetRecords) (respSmartsheetGetRecords, error) {
	var resp respSmartsheetGetRecords
	err := executeQyapiJSONPost(c, "/cgi-bin/wedoc/smartsheet/get_records", req, &resp, true)
	if err != nil {
		return respSmartsheetGetRecords{}, err
	}

	return resp, nil
}
