// Code generated by sdkcodegen; DO NOT EDIT.

package workwx

// reqWedriveSpaceCreate 新建空间请求
type reqWedriveSpaceCreate struct {
	// SpaceName 空间标题
	SpaceName string `json:"space_name"`
	// AuthInfo 空间其他成员信息
	AuthInfo []AuthInfo `json:"auth_info"`
	// SpaceSubType 区分创建空间类型, 0:普通（目前只支持0）
	SpaceSubType uint32 `json:"space_sub_type"`
}

// SpaceSubType 空间类型
type SpaceSubType uint32

// SpaceSubTypeNormal 普通
const SpaceSubTypeNormal SpaceSubType = 0

// AuthInfo 空间成员信息
type AuthInfo struct {
	// Type 成员类型 1:个人 2:部门
	Type uint32 `json:"type"`
	// Userid 成员userid
	Userid string `json:"userid,omitempty"`
	// Departmentid 部门departmentid
	Departmentid uint32 `json:"departmentid,omitempty"`
	// Auth 成员权限 1:仅下载 4:可预览 7:应用空间管理员
	Auth AuthType `json:"auth"`
}

// AuthType 表示微盘空间成员权限类型
type AuthType uint32

// 微盘成员权限类型常量
const (
	// AuthTypeDownloadOnly 仅下载权限
	AuthTypeDownloadOnly AuthType = 1
	// AuthTypePreview 可预览权限
	AuthTypePreview AuthType = 4
	// AuthTypeAdmin 应用空间管理员权限
	AuthTypeAdmin AuthType = 7
)

// respWedriveSpaceCreate 新建空间返回
type respWedriveSpaceCreate struct {
	// respCommon 通用响应
	respCommon
	// SpaceID 空间id
	SpaceID string `json:"spaceid"`
}

// wedriveCreateSpace https://developer.work.weixin.qq.com/document/path/96845
func (c *WorkwxApp) wedriveCreateSpace(req reqWedriveSpaceCreate) (respWedriveSpaceCreate, error) {
	var resp respWedriveSpaceCreate
	err := executeQyapiJSONPost(c, "/cgi-bin/wedrive/space_create", req, &resp, true)
	if err != nil {
		return respWedriveSpaceCreate{}, err
	}

	return resp, nil
}
